### ISSUE TITLE
ModuleNotFoundError: No module named 'mainGUI'

### ISSUE THREAD

**Issue by Jalkhov** [GDGVIT/pip-gui#32]
Hi, when i run the command to open the program give me the above error:

```
C:\Users\Pedro Torcatt>pipgui
Traceback (most recent call last):
  File "c:\users\pedro torcatt\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\pedro torcatt\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Pedro Torcatt\AppData\Local\Programs\Python\Python39\Scripts\pipgui.exe\__main__.py", line 4, in <module>
  File "c:\users\pedro torcatt\appdata\local\programs\python\python39\lib\site-packages\pipgui\__init__.py", line 2, in <module>
    from mainGUI import main
ModuleNotFoundError: No module named 'mainGUI'
```

**My python version:** Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32

**Comment by Cyberavater** [comment]
Any assistance on this one? I'm having the same issue here.

**Comment by GenericDataflow** [comment]
Same here

**Comment by SaurusXI** [comment]
Hi @Cyberavater @GuessJuice! Sorry for the late response. We're a little tied down with other work right now, so I'll take a few days to fix this. Meanwhile if you'd like to take a stab at the problem, please make a PR.

**Comment by SaurusXI** [comment]
Should be fixed now, please try installing the latest version of the package. Closing the issue for now, feel free to reopen if needed.
