### ISSUE TITLE
ImportError: DLL load failed while importing QtCore...

### ISSUE THREAD

**Issue by jrep41** [GDGVIT/pip-gui#42]
PS C:\Users\joser> pipgui
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\joser\AppData\Local\Programs\Python\Python312\Scripts\pipgui.exe\__main__.py", line 4, in <module>
  File "C:\Users\joser\AppData\Local\Programs\Python\Python312\Lib\site-packages\pipgui\__main__.py", line 8, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed while importing QtCore: No se puede encontrar el módulo especificado.
PS C:\Users\joser>

**Comment by jrep41** [comment]
DEPRECATION: Loading egg at c:\users\joser\appdata\local\programs\python\python312\lib\site-packages\pyqt5-5.15.10-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\joser\appdata\local\programs\python\python312\lib\site-packages\pyqt5_qt5-5.15.2-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\joser\appdata\local\programs\python\python312\lib\site-packages\pyqt5_sip-12.13.0-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330

updating versions...
